name: CLI action
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build
      run: npm run build
    - name: Run Commands
      run: |
        ./bin/run init --help
        ./bin/run build --help
        ./bin/run run --help
        ./bin/run watch --help
        ./bin/run upload --help
        ./bin/run update --help
